# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_auto_20160614_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
