# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_skill_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='skills',
            field=models.ManyToManyField(blank=True, to='journal.Skill'),
        ),
    ]
